### ISSUE TITLE
Remove generics in key_builder

### ISSUE THREAD

**Issue by garrensmith** [tigrisdata/tigris#1027]
The [Key_builder](https://github.com/tigrisdata/tigris/blob/main/query/filter/key_builder.go) supports generics to allow `schema.Field` or `schema.QueryableField`. This should be removed and `key_builder` should only accept `schema.QueryableField`. 

Steps to get this working:
1. Remove generics in key_builder
2. Fix tests to only accept `schema.QueryableField` this could be done by converting the current `schema.Field` options into a `queryableField` before running the test
3. Add a method on `schema.DefaultCollection` to get the primarykeys as a list of queryablefields

**Comment by karuppiah7890** [comment]
I'll pick this up

**Comment by karuppiah7890** [comment]
Related Discord discussion thread - https://discord.com/channels/1033842669983633488/1033843208192524348/1095960587806183494
