### ISSUE TITLE
Change data streaming

### ISSUE THREAD

**Issue by ovaistariq** [tigrisdata/tigris#180]

**Comment by sam-goodwin** [comment]
What was the conclusion here? I'd love to start using Tigris, but I use AWS serverless and heavily rely on change data capture for my event-driven systems. I'm investigating replacing DynamoDB with Tigris but the streaming solutions of tigris require a persistent server. Is it possible to stream change events to Lambda like an Event source. Or perhaps stream them out to Kinesis/Kafka/etc.?
