### ISSUE TITLE
Database creation in parallel

### ISSUE THREAD

**Issue by seeforschauer** [tigrisdata/tigris#243]
**Describe the bug**
For tests, I run several requests to create databases in parallel.
Sometimes the error for database creation is nil however database is absent. 
Sometimes the error does appear.

**To Reproduce**
1. put files in one folder, run `go mod tidy`
2. run `go test -count=1 ./...` 

**Expected behavior**
Expected 3 databases to be present: 
```
skydancer:~/tigriscli$ tigris list databases
testthree
testtwo
testone
```

**Screenshots**
Instead, the error appears:
```
skydancer:~/tigriscli$ go test -count=1 ./... 
--- FAIL: TestThree (0.01s)
    tigriscli_test.go:37: recreate db testthree
    tigriscli_test.go:40: 
        	Error Trace:	tigriscli_test.go:40
        	            				tigriscli_test.go:25
        	Error:      	Received unexpected error:
        	            	database already exist
        	Test:       	TestThree
FAIL
FAIL	tigriscli	0.054s
FAIL
```
and the databases list if not full, 
```
skydancer:~/tigriscli$ tigris list databases
testthree
testtwo
```
The name of the absent database `testone` is not the `testthree` that appeared in the error message. 

**Desktop (please complete the following information):**
`Linux skydancer 5.11.0-49-generic #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**

* cli `tigris version v1.0.0-alpha.8`
* tigris container date `docker inspect --format '{{ .Created }}'  tigrisdata/tigris:latest 
2022-05-04T01:53:00.992143876Z`
* `github.com/tigrisdata/tigris-client-go v1.0.0-alpha.10`

**Comment by seeforschauer** [comment]
```
package main

import (
	"context"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/tigrisdata/tigris-client-go/config"
	"github.com/tigrisdata/tigris-client-go/driver"
)

func TestOne(t *testing.T) {
	t.Parallel()
	setup(t)
}

func TestTwo(t *testing.T) {
	t.Parallel()
	setup(t)
}

func TestThree(t *testing.T) {
	t.Parallel()
	setup(t)
}

func setup(t *testing.T) {

	ctx := context.TODO()
	drv, err := driver.NewDriver(ctx, &config.Config{URL: url})
	if err != nil {
		panic(err)
	}

	databaseName := getDBName(t)
	t.Log("recreate db", databaseName)
	// _ = drv.DropDatabase(ctx, databaseName)
	err = drv.CreateDatabase(ctx, databaseName)
	require.NoError(t, err)
}

func getDBName(t *testing.T) string {
	name := strings.ToLower(t.Name())
	name = strings.ReplaceAll(name, "/", "-")
	name = strings.ReplaceAll(name, " ", "-")

	require.Less(t, len(name), 64)
	return name
}
```

**Comment by himank** [comment]
Pushing the diff out and now you should see a transaction conflicting error if the conflicting transaction is causing create to not succeed. Earlier this was getting masked and therefore CreateDatabase was returning success even though there was a conflict and the request didn't succeed. 

`➜  tigris git:(bump) ✗ curl -H "content-type:application/json" -s -X POST '127.0.0.1:8081/api/v1/databases/list'
{"databases":[{"db":"db1"},{"db":"db2"}]}

➜  tigris git:(bump)  go test -count=1 -tags=integration -v ./test/v1/db_test/...
=== RUN   TestOne
=== PAUSE TestOne
=== RUN   TestTwo
=== PAUSE TestTwo
=== RUN   TestThree
=== PAUSE TestThree
=== CONT  TestOne
localhost:8081
=== CONT  TestThree
localhost:8081
=== CONT  TestTwo
localhost:8081
=== CONT  TestThree
    db_test.go:40: recreate db testthree
=== CONT  TestTwo
    db_test.go:40: recreate db testtwo
=== CONT  TestOne
    db_test.go:40: recreate db testone
--- PASS: TestThree (0.03s)
Code:  Aborted
Code:  Aborted
=== CONT  TestTwo
    db_test.go:46:
        	Error Trace:	db_test.go:46
        	            				db_test.go:23
        	Error:      	Received unexpected error:
        	            	transaction not committed due to conflict with another transaction
        	Test:       	TestTwo
--- FAIL: TestTwo (0.07s)
=== CONT  TestOne
    db_test.go:46:
        	Error Trace:	db_test.go:46
        	            				db_test.go:18
        	Error:      	Received unexpected error:
        	            	transaction not committed due to conflict with another transaction
        	Test:       	TestOne
--- FAIL: TestOne (0.07s)
FAIL
FAIL	github.com/tigrisdata/tigris/test/v1/db_test	0.205s
FAIL`

**Comment by AlekSi** [comment]
Thank you. So will you fix it, or we (and all clients) should not create databases with different names in parallel?

**Comment by himank** [comment]
We have fixed it, sorry for late replying. Database creation in parallel is allowed. We have also added server side retries to minimize the conflicts. Please give it a try. Closing it.

**Comment by seeforschauer** [comment]
Thank you, it works :)
