### ISSUE TITLE
EventStream API not working in TypeScript SDK

### ISSUE THREAD

**Issue by Anshuman71** [tigrisdata/tigris#384]
**Describe the bug**
I get the following error while requesting the `/events` API endpoint.

![image](https://user-images.githubusercontent.com/28081510/181405397-6fe9c379-bbd9-41bb-868d-d59f1a91dba0.png)

**To Reproduce**
1. Clone the TypeScript quickstart repository
2. Request `http://localhost:8081/api/v1/databases/hello-db/collections/users/events` in Postman
3. Run `npm start` in terminal

**Expected behavior**
Get a stream of events of inserted documents.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Version 12.4 (21F79)

**Additional context**

**Comment by himank** [comment]
We have fixed the bug and released the server with the fix. Please let us know if you still see any issues.
