### ISSUE TITLE
Container Resource Limits

### ISSUE THREAD

**Issue by asjadjawed** [tigrisdata/tigris#547]
**Describe the bug**
Containers should have resource limits

deployment/manifests/base/deployment.yaml
deployment/manifests/base/search-deployment.yaml

**Expected behavior**
Without resource limits, containers can starve other processes

**Comment by ovaistariq** [comment]
@rbarabas you probably want to look into this one as you are working on k8s deployment manifests.

**Comment by rbarabas** [comment]
Absolutely! 

Thanks for reporting this @asjadjawed! I agree that we should define limits for all of these even for the base manifests.

We are currently in the process of revising the example manifest and are going to replace these manifests with those defined in https://github.com/tigrisdata/tigris-deploy. I will take your recommendation and apply to the base manifests there! Stay tuned.

**Comment by rbarabas** [comment]
Just a heads up that the [Helm charts](https://github.com/tigrisdata/tigris-deploy/tree/main/helm) based install has been released and the templated manifest under `helm` should all have resource limits defined. 

The default `values.yaml` will deploy with grant more resources to the deployment while `values-local.yaml` will limit resources significantly for a laptop like installation.

Once we also switch over to using the Charts I'm going to open a PR to remove the old `raw` manifests from both this repository and `tigris-deploy`.

**Comment by rbarabas** [comment]
Closing this issue as addressed. PR #577 has moved the deployment files out of this repository and the Helm chart based installation should cover this. Thanks again for taking the time to report this! ❤️
