### ISSUE TITLE
Key Concepts link is broken in README

### ISSUE THREAD

**Issue by nicolasff** [tigrisdata/tigris#568]
**Describe the bug**
In the README, the first section titled "Helpful Links" contains a list of links that starts with "Key Concepts". This link is broken.
It points to https://docs.tigrisdata.com/overview/concepts, which gives a 404.

**To Reproduce**
1. Go to ["Helpful Links" in the README](https://github.com/tigrisdata/tigris#helpful-links)
2. Click on "Key Concepts"
3. Arrive on [a page that says "Page Not Found"](https://docs.tigrisdata.com/overview/concepts)

**Expected behavior**
A page about key concepts of Tigris

**Screenshots**
<img width="817" alt="image" src="https://user-images.githubusercontent.com/7276/193415410-e960966f-ff5b-4ec9-9109-0cea3efa8834.png">

**Desktop (please complete the following information):**
All.

**Comment by ovaistariq** [comment]
Thanks for reporting the issue, its been fixed.
