### ISSUE TITLE
Concurrent requests with `number` values in the filter fail from time to time

### ISSUE THREAD

**Issue by rumyantseva** [tigrisdata/tigris#837]
**Describe the bug**

We noticed that from time to time, our tests that call Tigris fail when we run them as usual (in parallel), but pass if we set `-parallel=1.` After some investigation, I was able to reproduce this behavior with a smaller data set.

[Here](https://github.com/FerretDB/tigris-experiments/blob/scientific/main.go#L69) I have an example where I set `"balance": 5e-40` and then search for it. Everything works as expected. I tried running it multiple times, and it always finds and returns the expected result.

[Here](https://github.com/FerretDB/tigris-experiments/blob/parallel-requests/main.go) I have an example where I also set `"balance": 5e-40`, but I do some parallel requests to the collections. In this case, Tigris can’t find the records for the filter with  `"balance": 5e-40`. However, if I set the filter as`"balance": 5e-20`., everything works as expected, and I can find it even if I send parallel requests.  

**To Reproduce**
Run https://github.com/FerretDB/tigris-experiments/blob/parallel-requests/main.go, it will not find the record for the filter `"balance": 5e-40`.

**Expected behavior**
It is possible to find such records even if there is a number of parallel requests sent.

**Desktop (please complete the following information):**
 - OS: macOS 13.2
 - Server: `tigrisdata/tigris-local:1.0.0-beta.36` (docker image), driver: `github.com/tigrisdata/tigris-client-go v1.0.0-beta.22`.

**Comment by himank** [comment]
This is not related to concurrency but the floating point handling when the value can’t fit in 32-bit. The indexing of floating numbers was parsing the floating values in float(32bit) which means there were two problems:
- The smallest floating point normal number needed to be less than ~ 1.1755e-38
- The number has to be in the range -3.4e38/3.4e38

Outside of this range, an error was getting swallowed, resulting in empty documents returned for that query. 

I have fixed it to ensure the full 64-bit range is covered and also made sure that errors are returned in similar cases.
