### ISSUE TITLE
Allow to use `_` in the beginning of collection and field names

### ISSUE THREAD

**Issue by rumyantseva** [tigrisdata/tigris#839]
**Is your feature request related to a problem? Please describe.**

To support some cases reported by FerretDB users, we need to support collection and field names starting from `_` symbol.
Currently, such symbols are restricted, so that would be nice to allow them.

Currently, multiple users are blocked by such restrictions and can't migrate to FerretDB.

**Additional context** 

https://github.com/tigrisdata/tigris/blob/65470a25712e728de316b22a04bfee406d517167/api/server/v1/validator.go#L21

**Comment by himank** [comment]
Field names already allow `_` as a first character, I have also pushed a change to allow it for collection names.
