### ISSUE TITLE
Report search index size metrics

### ISSUE THREAD

**Issue by ovaistariq** [tigrisdata/tigris#886]
Similar to collection size metrics, we need to report the search index size metrics

**Comment by akhill10** [comment]
@ovaistariq Can I work on this?
I went through the metrics code. Got a sense of how it has been done for collection size metrics.

- We can collect `system_disk_used_bytes` from the [mertics API](https://typesense.org/docs/0.22.0/api/cluster-operations.html#cluster-metrics) of typesense. But this is for the whole search cluster and Typesense doesn't provide any information on usage by index ( collection in Typesense).  Is there a way we can get the size by index?
- [Typesense Collection Retrieve](https://typesense.org/docs/0.22.0/api/collections.html?#retrieve-a-collection) provides the details on a number of documents in the index. Is it useful to report?

What are all tags we are looking to report ?
`tigris_tenant, tigris_tenant_name, project, db, branch, index `

**Comment by efirs** [comment]
Hi, @akhill10!
Thanks for your interest in contributing!

As a first step we need to implement search counter part tenant.CollectionSize.
Where we need to use `tenant.Encoder.EncodeFDBSearchTableName(index.StoreIndexName())` as a KV store table name.
Also we need to add `tenant.ProjectSearchSize()` and `tenant.SearchSize()`,
this can be done using `tenant.ListSearchIndexes` similar to `tenant.DatabaseSize()` and `tenant.Size()`.

Then we need to wire it in the quote package where we emit metrics.
See `storage.updateMetricsForNamespace`.

Let me know if you need more information.

**Comment by akhill10** [comment]
Thanks @himank  @efirs , that was very helpful. Raised PR please take a look.

**Comment by ovaistariq** [comment]
Fixed by #1113
