### ISSUE TITLE
Instrument the query type whether it is a secondary index read or a full table scan

### ISSUE THREAD

**Issue by ovaistariq** [tigrisdata/tigris#897]
We need to report metrics such as reads performed through secondary indexes, reads performed through full table scans, etc. This will allow us to validate what types of queries are using secondary indexes vs which ones are not.

**Comment by himank** [comment]
@pboros I think this is done?

**Comment by pboros** [comment]
I checked this, this is done. The read_type tag is populated with "secondary" if the read is from a secondary index.
