### ISSUE TITLE
Report usage based metrics

### ISSUE THREAD

**Issue by ovaistariq** [tigrisdata/tigris#918]
We need to report usage-based metrics as follows:
- read units (4KB size) consumed
- write units (1KB size) consumed: this is the record size + secondary indexed field size
- search units consumed: 1 request is one search unit
- search index size
- dataset size uncompressed

**Comment by ovaistariq** [comment]
Discussed with @pboros who is interested in taking this

**Comment by himank** [comment]
Great, let's sync on it Peter. There are a few things we need to modify related to reporting of Update/Delete workload.

**Comment by efirs** [comment]
Sorry, just read this. I've pushed the change to account update/delete: https://github.com/tigrisdata/tigris/pull/921

It's doesn't account secondary indexes, search and compression.
